<?xml version="1.0"?>
<!--
Copyright (c) 2008 Corel Corporation.

Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying 
documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, 
and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject 
to the following:

The copyright notices in the Software and this entire statement, including the above license grant, the original location it was 
downloaded from, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, 
and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object
code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. THE SOFTWARE MAY CONTAIN BUGS, ERRORS AND OTHER
PROBLEMS THAT COULD CAUSE SYSTEM FAILURES AND THE USE OF SUCH SOFTWARE IS ENTIRELY AT THE USER'S RISK. IN NO EVENT SHALL THE COPYRIGHT
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

************************************************************************************************************************************
This file adds controls to the current workspace.  It is only executed once per workspace (e.g. if you make changes, you must launch 
with F8 to reapply the changes.
************************************************************************************************************************************
-->
<xsl:stylesheet version="1.0"
								xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
								xmlns:frmwrk="Corel Framework Data"
								exclude-result-prefixes="frmwrk">
  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>

  <!-- Use these elements for the framework to move the container from the app config file to the user config file -->
  <!-- Since these elements use the frmwrk name space, they will not be executed when the XSLT is applied to the user config file -->
	<frmwrk:uiconfig>
		<!-- The Application Info should always be the topmost frmwrk element -->
		<frmwrk:compositeNode xPath="/uiConfig/commandBars/commandBarData[@guid='74e03d83-404c-49f5-824a-fe0fd02ab29a']"/>
		<frmwrk:compositeNode xPath="/uiConfig/commandBars/commandBarData[@guid='1056b8d8-9185-46ee-af8e-77c7ba383a4e']"/>
		<frmwrk:compositeNode xPath="/uiConfig/commandBars/commandBarData[@guid='c2b44f69-6dec-444e-a37e-5dbf7ff43dae']"/>
		<frmwrk:compositeNode xPath="/uiConfig/views/viewTemplate[@guid='ab303a90-464d-5191-423f-613c4d1dcb2c']"/>
		<frmwrk:compositeNode xPath="/uiConfig/frame"/>
	</frmwrk:uiconfig>

  <!-- Copy everything -->
  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>
	<!-- Copy everything -->
	<xsl:template match="node()|@*">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>
		</xsl:copy>
	</xsl:template>
	<!-- Helper to insert a new item into a menu/toolbar -->
	<xsl:template match="node()|@*" mode="insert-item">
		<xsl:param name="after"></xsl:param>
		<xsl:param name="before"></xsl:param>
		<xsl:param name="content"></xsl:param>
		<xsl:copy>
			<xsl:apply-templates select="@*"/>
			<xsl:for-each select="node()">
				<xsl:if test="name()='item' and @guidRef=$before">
					<xsl:copy-of select="$content"/>
				</xsl:if>
				<xsl:copy>
					<xsl:apply-templates select="node()|@*"/>
				</xsl:copy>
				<xsl:if test="name()='item' and @guidRef=$after">
					<xsl:copy-of select="$content"/>
				</xsl:if>
			</xsl:for-each>
			<xsl:if test="not(./item[@guidRef=$after]) and not(./item[@guidRef=$before])">
				<xsl:copy-of select="$content"/>
			</xsl:if>
		</xsl:copy>
	</xsl:template>
	<!-- Add the spinner in Property Bar Mode '1fa965b7-64d1-4219-8d91-5904006b7cb5' ellipse tool property bar mode-->
	<xsl:template match="commandBarData[@guid='74e03d83-404c-49f5-824a-fe0fd02ab29a']/toolbar/modeData">
		<xsl:apply-templates  mode="insert-item" select=".">
			<xsl:with-param name="content">
				<!-- Make sure we don't read the menu item it it already exists -->
				<xsl:if test="not(./item[@guidRef='204731af-49f0-4af4-9c35-4b3df6421b59'])">
					<item guidRef="204731af-49f0-4af4-9c35-4b3df6421b59"/>
				</xsl:if>
			</xsl:with-param>
			<!-- Place ours spinner after the original spinner -->
			<xsl:with-param name="after" select = "'325d7c86-da3a-4610-bd25-5cf98cf66a41'"/>

		</xsl:apply-templates>
	</xsl:template>

	<!-- Put the Warpper control at the end of the 'standard command bar' -->
  <xsl:template match="commandBarData[@guid='c2b44f69-6dec-444e-a37e-5dbf7ff43dae']/toolbar">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
      <!-- Make sure we don't read the menu item it it already exists -->
      <xsl:if test="not(./item[@guidRef='3b452f50-64ab-43fd-b9cc-6ef5a9ad9e87'])">
				<item guidRef="3b452f50-64ab-43fd-b9cc-6ef5a9ad9e87"/>
			</xsl:if>
    </xsl:copy>
  </xsl:template>
  
</xsl:stylesheet>